<?php

namespace Database\Seeders;

use App\Models\Setting;
use Illuminate\Database\Seeder;

class SettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            // ==========================================
            // GENERAL GROUP
            // ==========================================
            [
                'key' => 'general.site_name',
                'group' => 'general',
                'value' => 'Seruwit CMS',
                'type' => 'text',
                'label' => 'Site Name',
                'description' => 'The name of your website displayed in the browser title and header.',
                'is_public' => true,
                'sort_order' => 1,
            ],
            [
                'key' => 'general.site_tagline',
                'group' => 'general',
                'value' => 'Drag & Drop CMS with E-Commerce',
                'type' => 'text',
                'label' => 'Site Tagline',
                'description' => 'A short description or slogan for your website.',
                'is_public' => true,
                'sort_order' => 2,
            ],
            [
                'key' => 'general.site_description',
                'group' => 'general',
                'value' => 'Seruwit adalah CMS Drag-and-Drop berbasis Laravel dengan kemampuan e-commerce terintegrasi.',
                'type' => 'textarea',
                'label' => 'Site Description',
                'description' => 'A longer description of your website for SEO purposes.',
                'is_public' => true,
                'sort_order' => 3,
            ],
            [
                'key' => 'general.admin_email',
                'group' => 'general',
                'value' => 'admin@seruwit.com',
                'type' => 'email',
                'label' => 'Admin Email',
                'description' => 'Primary email address for administrative notifications.',
                'is_public' => false,
                'sort_order' => 4,
            ],
            [
                'key' => 'general.timezone',
                'group' => 'general',
                'value' => 'Asia/Jakarta',
                'type' => 'text',
                'label' => 'Timezone',
                'description' => 'Default timezone for the application.',
                'is_public' => false,
                'sort_order' => 5,
            ],
            [
                'key' => 'general.date_format',
                'group' => 'general',
                'value' => 'd M Y',
                'type' => 'text',
                'label' => 'Date Format',
                'description' => 'Default date format (PHP date format).',
                'is_public' => true,
                'sort_order' => 6,
            ],
            [
                'key' => 'general.maintenance_mode',
                'group' => 'general',
                'value' => '0',
                'type' => 'boolean',
                'label' => 'Maintenance Mode',
                'description' => 'Enable maintenance mode to show a maintenance page to visitors.',
                'is_public' => false,
                'sort_order' => 7,
            ],

            // ==========================================
            // SITE GROUP
            // ==========================================
            [
                'key' => 'site.logo',
                'group' => 'site',
                'value' => '/images/logo.png',
                'type' => 'text',
                'label' => 'Site Logo',
                'description' => 'URL or path to the site logo image.',
                'is_public' => true,
                'sort_order' => 1,
            ],
            [
                'key' => 'site.favicon',
                'group' => 'site',
                'value' => '/favicon.ico',
                'type' => 'text',
                'label' => 'Favicon',
                'description' => 'URL or path to the favicon.',
                'is_public' => true,
                'sort_order' => 2,
            ],
            [
                'key' => 'site.copyright',
                'group' => 'site',
                'value' => '© 2026 Seruwit CMS. All rights reserved.',
                'type' => 'text',
                'label' => 'Copyright Text',
                'description' => 'Copyright text displayed in the footer.',
                'is_public' => true,
                'sort_order' => 3,
            ],
            [
                'key' => 'site.phone',
                'group' => 'site',
                'value' => '+62 21 1234 5678',
                'type' => 'text',
                'label' => 'Phone Number',
                'description' => 'Contact phone number.',
                'is_public' => true,
                'sort_order' => 4,
            ],
            [
                'key' => 'site.address',
                'group' => 'site',
                'value' => 'Jl. Sudirman No. 123, Jakarta Pusat, Indonesia',
                'type' => 'textarea',
                'label' => 'Address',
                'description' => 'Physical address of your business.',
                'is_public' => true,
                'sort_order' => 5,
            ],
            [
                'key' => 'site.contact_email',
                'group' => 'site',
                'value' => 'contact@seruwit.com',
                'type' => 'email',
                'label' => 'Contact Email',
                'description' => 'Public contact email address.',
                'is_public' => true,
                'sort_order' => 6,
            ],
            [
                'key' => 'site.working_hours',
                'group' => 'site',
                'value' => 'Senin - Jumat: 09:00 - 17:00',
                'type' => 'text',
                'label' => 'Working Hours',
                'description' => 'Business working hours.',
                'is_public' => true,
                'sort_order' => 7,
            ],

            // ==========================================
            // SEO GROUP
            // ==========================================
            [
                'key' => 'seo.meta_title',
                'group' => 'seo',
                'value' => 'Seruwit CMS - Drag & Drop Website Builder',
                'type' => 'text',
                'label' => 'Default Meta Title',
                'description' => 'Default meta title for pages without a specific title.',
                'is_public' => true,
                'sort_order' => 1,
            ],
            [
                'key' => 'seo.meta_description',
                'group' => 'seo',
                'value' => 'Build beautiful websites with Seruwit CMS. Drag-and-drop editor, e-commerce ready, and fully customizable.',
                'type' => 'textarea',
                'label' => 'Default Meta Description',
                'description' => 'Default meta description for SEO.',
                'is_public' => true,
                'sort_order' => 2,
            ],
            [
                'key' => 'seo.meta_keywords',
                'group' => 'seo',
                'value' => 'cms, website builder, drag and drop, e-commerce, laravel',
                'type' => 'text',
                'label' => 'Default Meta Keywords',
                'description' => 'Default meta keywords (comma separated).',
                'is_public' => true,
                'sort_order' => 3,
            ],
            [
                'key' => 'seo.google_analytics_id',
                'group' => 'seo',
                'value' => '',
                'type' => 'text',
                'label' => 'Google Analytics ID',
                'description' => 'Google Analytics tracking ID (e.g., G-XXXXXXXXXX).',
                'is_public' => false,
                'sort_order' => 4,
            ],
            [
                'key' => 'seo.google_tag_manager_id',
                'group' => 'seo',
                'value' => '',
                'type' => 'text',
                'label' => 'Google Tag Manager ID',
                'description' => 'Google Tag Manager container ID (e.g., GTM-XXXXXXX).',
                'is_public' => false,
                'sort_order' => 5,
            ],
            [
                'key' => 'seo.robots_txt',
                'group' => 'seo',
                'value' => "User-agent: *\nAllow: /",
                'type' => 'textarea',
                'label' => 'Robots.txt Content',
                'description' => 'Content for robots.txt file.',
                'is_public' => false,
                'sort_order' => 6,
            ],
            [
                'key' => 'seo.og_image',
                'group' => 'seo',
                'value' => '/images/og-image.jpg',
                'type' => 'text',
                'label' => 'Default OG Image',
                'description' => 'Default Open Graph image for social sharing.',
                'is_public' => true,
                'sort_order' => 7,
            ],

            // ==========================================
            // SOCIAL GROUP
            // ==========================================
            [
                'key' => 'social.facebook',
                'group' => 'social',
                'value' => 'https://facebook.com/seruwit',
                'type' => 'url',
                'label' => 'Facebook URL',
                'description' => 'Facebook page URL.',
                'is_public' => true,
                'sort_order' => 1,
            ],
            [
                'key' => 'social.instagram',
                'group' => 'social',
                'value' => 'https://instagram.com/seruwit',
                'type' => 'url',
                'label' => 'Instagram URL',
                'description' => 'Instagram profile URL.',
                'is_public' => true,
                'sort_order' => 2,
            ],
            [
                'key' => 'social.twitter',
                'group' => 'social',
                'value' => 'https://twitter.com/seruwit',
                'type' => 'url',
                'label' => 'Twitter/X URL',
                'description' => 'Twitter/X profile URL.',
                'is_public' => true,
                'sort_order' => 3,
            ],
            [
                'key' => 'social.youtube',
                'group' => 'social',
                'value' => 'https://youtube.com/@seruwit',
                'type' => 'url',
                'label' => 'YouTube URL',
                'description' => 'YouTube channel URL.',
                'is_public' => true,
                'sort_order' => 4,
            ],
            [
                'key' => 'social.linkedin',
                'group' => 'social',
                'value' => 'https://linkedin.com/company/seruwit',
                'type' => 'url',
                'label' => 'LinkedIn URL',
                'description' => 'LinkedIn company page URL.',
                'is_public' => true,
                'sort_order' => 5,
            ],
            [
                'key' => 'social.tiktok',
                'group' => 'social',
                'value' => '',
                'type' => 'url',
                'label' => 'TikTok URL',
                'description' => 'TikTok profile URL.',
                'is_public' => true,
                'sort_order' => 6,
            ],
            [
                'key' => 'social.whatsapp',
                'group' => 'social',
                'value' => '+6281234567890',
                'type' => 'text',
                'label' => 'WhatsApp Number',
                'description' => 'WhatsApp contact number (with country code).',
                'is_public' => true,
                'sort_order' => 7,
            ],

            // ==========================================
            // EMAIL GROUP
            // ==========================================
            [
                'key' => 'email.from_name',
                'group' => 'email',
                'value' => 'Seruwit CMS',
                'type' => 'text',
                'label' => 'Email From Name',
                'description' => 'Name displayed as the sender in emails.',
                'is_public' => false,
                'sort_order' => 1,
            ],
            [
                'key' => 'email.from_address',
                'group' => 'email',
                'value' => 'noreply@seruwit.com',
                'type' => 'email',
                'label' => 'Email From Address',
                'description' => 'Email address used as the sender.',
                'is_public' => false,
                'sort_order' => 2,
            ],
            [
                'key' => 'email.reply_to',
                'group' => 'email',
                'value' => 'support@seruwit.com',
                'type' => 'email',
                'label' => 'Reply-To Address',
                'description' => 'Email address for replies.',
                'is_public' => false,
                'sort_order' => 3,
            ],
            [
                'key' => 'email.footer_text',
                'group' => 'email',
                'value' => 'This email was sent by Seruwit CMS. If you have any questions, please contact us.',
                'type' => 'textarea',
                'label' => 'Email Footer Text',
                'description' => 'Text displayed in the footer of all emails.',
                'is_public' => false,
                'sort_order' => 4,
            ],
            [
                'key' => 'email.notification_enabled',
                'group' => 'email',
                'value' => '1',
                'type' => 'boolean',
                'label' => 'Enable Email Notifications',
                'description' => 'Enable or disable email notifications.',
                'is_public' => false,
                'sort_order' => 5,
            ],

            // ==========================================
            // ECOMMERCE GROUP (for future use)
            // ==========================================
            [
                'key' => 'ecommerce.currency',
                'group' => 'ecommerce',
                'value' => 'IDR',
                'type' => 'text',
                'label' => 'Currency Code',
                'description' => 'Default currency code (e.g., IDR, USD, EUR).',
                'is_public' => true,
                'sort_order' => 1,
            ],
            [
                'key' => 'ecommerce.currency_symbol',
                'group' => 'ecommerce',
                'value' => 'Rp',
                'type' => 'text',
                'label' => 'Currency Symbol',
                'description' => 'Currency symbol displayed before prices.',
                'is_public' => true,
                'sort_order' => 2,
            ],
            [
                'key' => 'ecommerce.tax_enabled',
                'group' => 'ecommerce',
                'value' => '1',
                'type' => 'boolean',
                'label' => 'Enable Tax',
                'description' => 'Enable tax calculation on orders.',
                'is_public' => false,
                'sort_order' => 3,
            ],
            [
                'key' => 'ecommerce.tax_rate',
                'group' => 'ecommerce',
                'value' => '11',
                'type' => 'number',
                'label' => 'Tax Rate (%)',
                'description' => 'Default tax rate percentage (e.g., 11 for PPN Indonesia).',
                'is_public' => false,
                'sort_order' => 4,
            ],
            [
                'key' => 'ecommerce.free_shipping_threshold',
                'group' => 'ecommerce',
                'value' => '500000',
                'type' => 'number',
                'label' => 'Free Shipping Threshold',
                'description' => 'Minimum order amount for free shipping.',
                'is_public' => true,
                'sort_order' => 5,
            ],
            [
                'key' => 'ecommerce.stock_management',
                'group' => 'ecommerce',
                'value' => '1',
                'type' => 'boolean',
                'label' => 'Enable Stock Management',
                'description' => 'Enable inventory/stock tracking.',
                'is_public' => false,
                'sort_order' => 6,
            ],
            [
                'key' => 'ecommerce.low_stock_threshold',
                'group' => 'ecommerce',
                'value' => '5',
                'type' => 'number',
                'label' => 'Low Stock Threshold',
                'description' => 'Quantity at which a product is considered low stock.',
                'is_public' => false,
                'sort_order' => 7,
            ],

            // ==========================================
            // APPEARANCE GROUP
            // ==========================================
            [
                'key' => 'appearance.primary_color',
                'group' => 'appearance',
                'value' => '#3B82F6',
                'type' => 'color',
                'label' => 'Primary Color',
                'description' => 'Primary brand color (hex code).',
                'is_public' => true,
                'sort_order' => 1,
            ],
            [
                'key' => 'appearance.secondary_color',
                'group' => 'appearance',
                'value' => '#10B981',
                'type' => 'color',
                'label' => 'Secondary Color',
                'description' => 'Secondary brand color (hex code).',
                'is_public' => true,
                'sort_order' => 2,
            ],
            [
                'key' => 'appearance.dark_mode',
                'group' => 'appearance',
                'value' => '0',
                'type' => 'boolean',
                'label' => 'Enable Dark Mode',
                'description' => 'Enable dark mode by default.',
                'is_public' => true,
                'sort_order' => 3,
            ],
            [
                'key' => 'appearance.font_family',
                'group' => 'appearance',
                'value' => 'Inter, sans-serif',
                'type' => 'text',
                'label' => 'Font Family',
                'description' => 'Default font family for the website.',
                'is_public' => true,
                'sort_order' => 4,
            ],
            [
                'key' => 'appearance.custom_css',
                'group' => 'appearance',
                'value' => '',
                'type' => 'textarea',
                'label' => 'Custom CSS',
                'description' => 'Custom CSS code to be injected into the site.',
                'is_public' => false,
                'sort_order' => 5,
            ],
            [
                'key' => 'appearance.custom_js',
                'group' => 'appearance',
                'value' => '',
                'type' => 'textarea',
                'label' => 'Custom JavaScript',
                'description' => 'Custom JavaScript code to be injected into the site.',
                'is_public' => false,
                'sort_order' => 6,
            ],
            // ==========================================
            // UNITS GROUP (for the Product module's Unit field)
            // ==========================================
            [
                'key' => 'unit.pcs',
                'group' => 'units',
                'value' => 'pcs',
                'type' => 'text',
                'label' => 'Pieces',
                'description' => 'Selectable unit option on the Product module\'s Unit field.',
                'is_public' => true,
                'sort_order' => 1,
            ],
            [
                'key' => 'unit.kg',
                'group' => 'units',
                'value' => 'kg',
                'type' => 'text',
                'label' => 'Kilogram',
                'description' => 'Selectable unit option on the Product module\'s Unit field.',
                'is_public' => true,
                'sort_order' => 2,
            ],
            [
                'key' => 'unit.box',
                'group' => 'units',
                'value' => 'box',
                'type' => 'text',
                'label' => 'Box',
                'description' => 'Selectable unit option on the Product module\'s Unit field.',
                'is_public' => true,
                'sort_order' => 3,
            ],
            [
                'key' => 'unit.liter',
                'group' => 'units',
                'value' => 'liter',
                'type' => 'text',
                'label' => 'Liter',
                'description' => 'Selectable unit option on the Product module\'s Unit field.',
                'is_public' => true,
                'sort_order' => 4,
            ],
            [
                'key' => 'unit.sak',
                'group' => 'units',
                'value' => 'sak',
                'type' => 'text',
                'label' => 'Sack',
                'description' => 'Selectable unit option on the Product module\'s Unit field.',
                'is_public' => true,
                'sort_order' => 5,
            ],
            [
                'key' => 'unit.karung',
                'group' => 'units',
                'value' => 'karung',
                'type' => 'text',
                'label' => 'Bag',
                'description' => 'Selectable unit option on the Product module\'s Unit field.',
                'is_public' => true,
                'sort_order' => 6,
            ],
            [
                'key' => 'unit.m3',
                'group' => 'units',
                'value' => 'm3',
                'type' => 'text',
                'label' => 'Cubic Meter',
                'description' => 'Selectable unit option on the Product module\'s Unit field.',
                'is_public' => true,
                'sort_order' => 7,
            ],
            [
                'key' => 'unit.batang',
                'group' => 'units',
                'value' => 'batang',
                'type' => 'text',
                'label' => 'Rod/Bar',
                'description' => 'Selectable unit option on the Product module\'s Unit field.',
                'is_public' => true,
                'sort_order' => 8,
            ],
        ];

        foreach ($settings as $setting) {
            Setting::updateOrCreate(
                ['key' => $setting['key']],
                $setting
            );
        }
    }
}
